### ISSUE TITLE
Hamlib 1.4 (a.k.a Hamlib 4)

### ISSUE THREAD

**Issue by zcx2020** [glenoverby/sdr-shell-v4#1]
I use sdr-shell -> DttSP -> usbsoftrock to control a softrock RXTX.

Just upgraded to wsjtx-2.0.1 which uses Hamlib 1.4 to communicate with sdr-shell.via the Hamlib NET rigctl device.

Hamlib's network control protocol has changed in version 1.4.

wsjt-x-2.0.1 sends a \chk_vfo command before sending a \dump_state command.  This fails because sdr-shell's hamlib server doesn't support \chk_vfo.

The code in rigctl.cpp needs to be changed to support wsjtx-2.0.1 Hamlib 1.4.

**Comment by glenoverby** [comment]
rigctl.cpp now accepts the chk_vfo command and returns a fixed response.  wsjtx v2.1.2 starts, using hamlib on port 19090.
